Add/remove message flag functions, event listener functions, store seqno with messages
chadxz/imap-simple pull request #19
Opened 2016-11-14 21:54 UTC by redpandatronicsuk

Hello,

I added wrapper functions to add and delete flags from messages, similar to the addMessageLabel function.

I also added event listener functions for receiving new mails, message updates (such as flag changes) and external message delete events. The functions are added to the config object, not sure if that is the best way to do it.

Also added to store the seqno along with messages, so we can identify messages when we receive the seqno from external delete events.

Cheers,
Dominik

2016-11-14 22:09 UTC, chadxz requested changes
Changes look good, just a few comments.

2016-11-14 22:09 UTC, chadxz commented on lib/imapSimple.js
> +    if (!callback && typeof (fetchOptions) === 'function') {
i agree with this change, but the parens should be removed because they're redundant

2016-11-14 22:09 UTC, chadxz commented on lib/imapSimple.js
> +        }
Do you mind adding documentation to describe when these events would be useful and the options to add listeners for them in the README?

2016-11-14 22:09 UTC, chadxz commented on lib/imapSimple.js
> +};
can you please document these two methods in the README?

2016-11-15 16:10 UTC, redpandatronicsuk commented on lib/imapSimple.js
> +    if (!callback && typeof (fetchOptions) === 'function') {
Didn't even know I made this change, must have been the VS Code auto-formatter

2016-11-15 16:11 UTC, redpandatronicsuk commented on lib/imapSimple.js
> +};
Added something to the readme. Feel free to change the text if you don't like or can improve it

2016-11-15 16:11 UTC, redpandatronicsuk commented on lib/imapSimple.js
> +        }
Added something to the readme. Feel free to change the text if you don't like or can improve it

2016-11-15 16:12 UTC, redpandatronicsuk commented
I made the changes. Not sure if they will ripple through or if I need to make another pull request. I'll make another one just in case.

2016-11-15 16:16 UTC, redpandatronicsuk commented
The button now only says View Pull Request, instead of Create Pull Request, so I suppose the changes do go through

2016-11-15 16:20 UTC, chadxz approved these changes

2016-11-15 16:20 UTC, merged

2016-11-15 16:39 UTC, chadxz commented
Thanks Dominik, published as imap-simple@3.1.0

2016-11-23 06:54 UTC, redpandatronicsuk commented
Thanks for accepting the PR Chad!