Feature append
chadxz/imap-simple pull request #41
Opened 2017-08-19 17:44 UTC by jhannes

I added the append command to save messages to a mailbox, following the coding style and documentation style of the rest of the codebase.

2017-08-21 14:57 UTC, chadxz requested changes
Thank you for the pull request! I think this is a good addition to the library, and appreciate you taking the time to add it. I've got a few requests but overall it looks good.

2017-08-21 14:57 UTC, chadxz commented on README.md
> +message to the currently open mailbox to another mailbox. `message` is a RFC-822 compatible MIME message. Valid `options` are *mailbox*, *flags* and *date*. When completed, either calls the provided
currently open mailbox **or** another mailbox

2017-08-21 14:57 UTC, chadxz commented on lib/imapSimple.js
> + * @memberof ImapSimple
```
@param {string} message The message to append to the mailbox
@param {object} [options]
@param {string} [options.mailbox] The mailbox to append the message to. 
  Defaults to the currently open mailbox.
@param {string|Array<string>} [options.flags] A single flag (e.g. 'Seen') or an array 
  of flags (e.g. ['Seen', 'Flagged']) to append to the message. Defaults to
  no flags.
```

The rest of the docs look good

2017-08-21 14:57 UTC, chadxz commented on README.md
> +- **append**(<*mixed*> message, <*object*> options, [<*function*> callback]) - *Promise* - Appends the argument
please mark the options object as optional too

2017-08-21 20:34 UTC, jhannes commented
I've made the requested changes. Thanks for teaching me about `@param ... options.flags`. I didn't realize that I could document like this and it's much better! :-)

2017-08-21 20:40 UTC, chadxz approved these changes

2017-08-21 20:40 UTC, merged

2017-08-21 20:48 UTC, chadxz commented
Released as imap-simple@3.2.0

2017-08-21 20:49 UTC, chadxz commented
Thank you for your contribution 🍻

2017-08-22 14:15 UTC, jhannes commented
🍻