Implement Delete function, fix #58
chadxz/imap-simple pull request #60
Opened 2019-03-26 16:25 UTC by synox

2019-03-26 17:19 UTC, chadxz requested changes

2019-03-26 17:19 UTC, chadxz commented on lib/imapSimple.js
> + * @param {string|Array} uid The messages uid
Try this for description: "The uid or array of uids indicating the messages to be deleted"

2019-03-26 17:19 UTC, chadxz commented
Will you also add a section to the README for the method?

2019-03-26 17:25 UTC, synox commented
yes ill do readme

2019-03-26 17:34 UTC, synox commented
Do you also want to uupdate the example "Open messages and delete them"?
Done for today, it's late here.

2019-03-26 17:47 UTC, chadxz commented
That'd be great

2019-03-27 08:36 UTC, synox commented
I would also need a search function without fetch, just to get the uids. Would you combine this with a second search+delete method, or handle in a separate feature?

One more question. My use case is simple, i want delete all mails older than 1 month. My code:

		debug(`deleting mails before ${deleteMailsBefore}`)
			let searchCriteria = [
				['!DELETED'],
				['BEFORE', deleteMailsBefore]
			];

		const imapUnderlying = this.connection.imap

		const uids = await new Promise((resolve, reject) => {
			imapUnderlying.search(searchCriteria, (err, uids) => {
				if (err) {
					reject(err)
				} else {
					resolve(uids || [])
				}
			})
		})

		if (uids.length === 0) {
			return
		}
		await this.connection.deleteMessage(uids)

2019-03-27 12:14 UTC, chadxz commented
Either one sounds reasonable. If you wanted a search without fetch we could make the search take an optional parameter to skip the fetch. Out we could add a deleteWhere that accepts search criteria.

2019-03-28 06:35 UTC, synox commented
done, you can merge

2020-03-30 12:03 UTC, TeNNoX commented
@chadxz Would be great if you could merge this, so it could be release - and also #49

2020-03-30 13:15 UTC, merged

2020-03-30 13:45 UTC, chadxz commented
Released as v5.0.0

Thanks for the nudge @TeNNoX